# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_project/SuperRacing/SuperRacing.cache/wt [current_project]
set_property parent.project_path D:/vivado_project/SuperRacing/SuperRacing.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/startpic.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_3/ready.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/collision.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_1/carshape.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/over.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/road.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_3/ready_320.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_4/over_320.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_0_1/road_320.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_1/newcar.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/usercarshape.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_5/enemyshape.coe
add_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/newcollision.coe
add_files -quiet d:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files d:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_1/blk_mem_gen_1.dcp]
add_files -quiet d:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp
set_property used_in_implementation false [get_files d:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp]
add_files -quiet D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.dcp
set_property used_in_implementation false [get_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_3/blk_mem_gen_3.dcp]
add_files -quiet d:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.dcp
set_property used_in_implementation false [get_files d:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.dcp]
add_files -quiet d:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.dcp]
add_files -quiet d:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.dcp
set_property used_in_implementation false [get_files d:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_5/blk_mem_gen_5.dcp]
read_verilog D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/imports/new/Definition.h
set_property file_type "Verilog Header" [get_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/imports/new/Definition.h]
read_verilog -library xil_defaultlib {
  D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/new/display7.v
  D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/new/RandomProductor.v
  D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/new/CollisionJudge.v
  D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/new/vga_sync.v
  D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/new/INPUTSIG_CONVERTOR.v
  D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/new/SCORE_RECORDER.v
  D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/new/CentralController.v
  D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/new/RAM_MANAGER.v
  D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/new/VGA.v
  D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/new/SuperRacing.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_project/SuperRacing/SuperRacing.srcs/constrs_1/new/test.xdc
set_property used_in_implementation false [get_files D:/vivado_project/SuperRacing/SuperRacing.srcs/constrs_1/new/test.xdc]


synth_design -top SuperRacing -part xc7a100tcsg324-1


write_checkpoint -force -noxdef SuperRacing.dcp

catch { report_utilization -file SuperRacing_utilization_synth.rpt -pb SuperRacing_utilization_synth.pb }
