# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/vivado_project/SuperRacing/SuperRacing.cache/wt [current_project]
set_property parent.project_path D:/vivado_project/SuperRacing/SuperRacing.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property is_locked true [get_files D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top blk_mem_gen_2 -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all blk_mem_gen_2_

write_checkpoint -force -noxdef blk_mem_gen_2.dcp

catch { report_utilization -file blk_mem_gen_2_utilization_synth.rpt -pb blk_mem_gen_2_utilization_synth.pb }

if { [catch {
  file copy -force D:/vivado_project/SuperRacing/SuperRacing.runs/blk_mem_gen_2_synth_1/blk_mem_gen_2.dcp D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir D:/vivado_project/SuperRacing/SuperRacing.ip_user_files/ip/blk_mem_gen_2]} {
  catch { 
    file copy -force D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_stub.v D:/vivado_project/SuperRacing/SuperRacing.ip_user_files/ip/blk_mem_gen_2
  }
}

if {[file isdir D:/vivado_project/SuperRacing/SuperRacing.ip_user_files/ip/blk_mem_gen_2]} {
  catch { 
    file copy -force D:/vivado_project/SuperRacing/SuperRacing.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_stub.vhdl D:/vivado_project/SuperRacing/SuperRacing.ip_user_files/ip/blk_mem_gen_2
  }
}
